name: 'Install Query Insights Dashboards with Plugin via Binary'

on: [push, pull_request]

env:
  CI: 1
  # avoid warnings like "tput: No value for $TERM and no -T specified"
  TERM: xterm
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: myStrongPassword123!

jobs:
  verify-binary-installation:
    name: Run binary installation
    strategy:
      fail-fast: false
      matrix:
        # TODO: add windows support when OSD core is stable on windows
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          path: plugin-source

      - name: Set env from opensearch_dashboards.json
        run: |
          opensearch_version=$(node -p "require('./opensearch_dashboards.json').opensearchDashboardsVersion")
          plugin_version=$(node -p "require('./package.json').version")
          echo "OPENSEARCH_VERSION=$opensearch_version" >> $GITHUB_ENV
          echo "PLUGIN_VERSION=$plugin_version" >> $GITHUB_ENV
        working-directory: plugin-source
        shell: bash

      - name: Set up JDK
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
        with:
          distribution: temurin
          java-version: 21

      - name: Download and Start OpenSearch
        run: |
          curl -SLO https://artifacts.opensearch.org/snapshots/core/opensearch/${{ env.OPENSEARCH_VERSION }}-SNAPSHOT/opensearch-min-${{ env.OPENSEARCH_VERSION }}-SNAPSHOT-linux-x64-latest.tar.gz
          tar -xzf opensearch-*.tar.gz && mv opensearch-${{ env.OPENSEARCH_VERSION }}-SNAPSHOT opensearch
          rm -f opensearch-*.tar.gz
          echo "cluster.routing.allocation.disk.threshold_enabled: false" >> ./opensearch/config/opensearch.yml
          ./opensearch/bin/opensearch &
          sleep 45
          curl http://localhost:9200/_cat/plugins -v
        shell: bash

      - name: Checkout OpenSearch-Dashboards
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          path: OpenSearch-Dashboards
          repository: opensearch-project/OpenSearch-Dashboards
          ref: 'main'
          fetch-depth: 0

      - name: Move plugin to OpenSearch-Dashboards plugins directory
        run: |
          mv plugin-source OpenSearch-Dashboards/plugins/query-insights-dashboards

      - name: Setup Node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version-file: './OpenSearch-Dashboards/.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        run: |
          YARN_VERSION=$(node -p "require('./OpenSearch-Dashboards/package.json').engines.yarn")
          echo "Installing yarn@$YARN_VERSION"
          npm i -g yarn@$YARN_VERSION
        shell: bash

      - name: Bootstrap OpenSearch Dashboards
        uses: nick-fields/retry@14672906e672a08bd6eeb15720e9ed3ce869cdd4 # v2
        with:
          timeout_minutes: 20
          max_attempts: 2
          command: yarn --cwd OpenSearch-Dashboards osd bootstrap --oss --single-version=loose

      - name: Build plugin
        run: yarn build
        working-directory: OpenSearch-Dashboards/plugins/query-insights-dashboards

      - name: Download OpenSearch Dashboards binary
        run: |
          curl -SLO https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/${{ env.OPENSEARCH_VERSION }}/latest/linux/x64/tar/builds/opensearch-dashboards/dist/opensearch-dashboards-min-${{ env.OPENSEARCH_VERSION }}-linux-x64.tar.gz
          tar -xzf opensearch-dashboards-*.tar.gz
          rm -f opensearch-dashboards-*.tar.gz
        shell: bash

      - name: Install plugin
        run: |
          ./opensearch-dashboards-${{ env.OPENSEARCH_VERSION }}-linux-x64/bin/opensearch-dashboards-plugin install file:${{ github.workspace }}/OpenSearch-Dashboards/plugins/query-insights-dashboards/build/queryInsightsDashboards-${{ env.PLUGIN_VERSION }}.zip

      - name: Start the binary
        run: |
          nohup ./bin/opensearch-dashboards &
        working-directory: opensearch-dashboards-${{ env.OPENSEARCH_VERSION }}-linux-x64
        shell: bash

      - name: Health check
        run: |
          timeout 300 bash -c 'while [[ "$(curl -k http://localhost:5601/api/status | jq -r '.status.overall.state')" != "green" ]]; do sleep 5; done'
        working-directory: opensearch-dashboards-${{ env.OPENSEARCH_VERSION }}-linux-x64
        shell: bash
